project:
  type: website
  output-dir: docs

website:
  title: "OTTR <img src='./resources/images/basic_otter_water.PNG' width = 35px>"
  favicon: resources/images/basic_otter_water.ico
  navbar:
    left:
      - text: "{{< fa home title='A home' >}}"
        href: index.qmd
      - text: "Quick Start"
        menu:
          - text: "Getting started"
            href: getting_started.qmd
          - text: "Cheatsheet gallery"
            href: cheatsheet_gallery.qmd
          - text: "Next steps"
            href: next_steps.qmd
          - text: "Example use cases"
            href: examples.qmd
      - text: "Build with OTTR"
        menu:
          - text: "Template"
            href: getting_started.qmd
          - text: "Start writing"
            href: writing_content_courses.qmd
          - text: "Enroll for sync updates"
            href: enroll_sync.qmd
          - text: "OTTR-fy existing repo"
            href: ottr-fy.qmd
          - text: "Giving credits {{< fa award title='An award' >}}"
            href: more_features_credits.qmd
          - text: "---"
          - text: "Highly Recommended Steps"
          - text: "Google Analytics {{< fa chart-line title='a line chart' >}}"
            href: more_features_ganalytic.qmd
          - text: "Citing sources {{< fa quote-left title='A left quotation mark' >}}"
            href: more_features_sources.qmd
          - text: "Google Docs {{< fa file title='a file folder' >}}"
            href: more_features_gdoc.qmd
          - text: "Borrowing chapters {{< fa bookmark title='A bookmark' >}}"
            href: more_features_borrowing.qmd
          - text: ""
          - text: "---"
          - text: "Additional Customizations"
          - text: "Style {{< fa palette title='A palette' >}}"
            href: customize-style.qmd
          - text: "Checks {{< fa robot title='A robot' >}}"
            href: customize-robots.qmd
          - text: "Docker {{< fa gears title='gears' >}}"
            href: customize-docker.qmd
      - text: "Publishing OTTR courses"
        menu:
          - text: "Bookdown"
            href: publishing_bookdown.qmd
          - text: "Coursera"
            href: publishing_coursera.qmd
          - text: "Leanpub"
            href: publishing_leanpub.qmd
      - text: "Troubleshooting {{< fa tools title='tools' >}}"
        href: faqs.qmd
      - text: "Contact {{< fa envelope title='An envelope' >}}"
        href: contact.qmd
      - text: "{{< fa brands github title='The GitHub logo' >}}"
        href: https://github.com/ottrproject/OTTR_Template


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    include-after-body: resources/footer.html
    page-layout: article
    link-external-newwindow: true
